### ISSUE TITLE
Incompatible type for element

### ISSUE THREAD

**Issue by maravtdm** [vbatts/sl-feeds#16]
Hi,
Me again ... :-)

$ **go get github.com/vbatts/sl-feeds/cmd/sl-feeds**
`#` github.com/vbatts/sl-feeds/cmd/sl-feeds
go/src/github.com/vbatts/sl-feeds/cmd/sl-feeds/main.go:24:7: erreur: incompatible type for element 1 in composite literal
   24 |   cli.StringFlag{
      |       ^
go/src/github.com/vbatts/sl-feeds/cmd/sl-feeds/main.go:28:7: erreur: incompatible type for element 2 in composite literal
   28 |   cli.StringFlag{
      |       ^
go/src/github.com/vbatts/sl-feeds/cmd/sl-feeds/main.go:32:7: erreur: incompatible type for element 3 in composite literal
   32 |   cli.BoolFlag{
      |       ^
go/src/github.com/vbatts/sl-feeds/cmd/sl-feeds/main.go:36:7: erreur: incompatible type for element 4 in composite literal
   36 |   cli.BoolFlag{
      |       ^`

**Comment by vbatts** [comment]
funny. I just had that, and thought it to be fixed with the inclusion of the `go.mod` file.
Might you try `go get -u github.com/vbatts/sl-feeds/cmd/sl-feeds`?
the `-u` also pulls updates of the package and deps.

**Comment by maravtdm** [comment]
Nop ...

```
go get -u github.com/vbatts/sl-feeds/cmd/sl-feeds
# github.com/vbatts/sl-feeds/cmd/sl-feeds
go/src/github.com/vbatts/sl-feeds/cmd/sl-feeds/main.go:24:7: erreur: incompatible type for element 1 in composite literal
   24 |   cli.StringFlag{
      |       ^
go/src/github.com/vbatts/sl-feeds/cmd/sl-feeds/main.go:28:7: erreur: incompatible type for element 2 in composite literal
   28 |   cli.StringFlag{
      |       ^
go/src/github.com/vbatts/sl-feeds/cmd/sl-feeds/main.go:32:7: erreur: incompatible type for element 3 in composite literal
   32 |   cli.BoolFlag{
      |       ^
go/src/github.com/vbatts/sl-feeds/cmd/sl-feeds/main.go:36:7: erreur: incompatible type for element 4 in composite literal
   36 |   cli.BoolFlag{
      |       ^
```

**Comment by vbatts** [comment]
k.
What's the output of `go version`?

**Comment by maravtdm** [comment]
I'm on slackware-current
```

go version
go version go1.14.4 gccgo (GCC) 10.2.0 linux/amd64
```

**Comment by vbatts** [comment]
ah okay. Slackware defaults to the "gcc-go" included in the gcc compiler suite, which is sometimes good enough, but usually folks use it to compile the upstream golang compiler (https://slackbuilds.org/repository/14.2/development/google-go-lang/)
Regardless, I'll try this on slackware64-current, on the gcc-go and report back.

**Comment by maravtdm** [comment]
Thx

**Comment by vbatts** [comment]
ok. try again with the `go get -u ...`
