### ISSUE TITLE
X509 issue

### ISSUE THREAD

**Issue by maravtdm** [vbatts/sl-feeds#18]
Hi,

Me again :-)
I have an X509 issue with Slackers repo : 
`
2021/04/03 12:57:00 slackware64-current Get "https://slack.conraid.net/repository//slackware64-current/ChangeLog.txt": x509: certificate signed by unknown authority`

But in the web browser, no issue
Can we do something about it ?

**Comment by maravtdm** [comment]
I checked all of the hosts (+ mine "matoda.pw") on https://checkhost.unboundtest.com/checkhost
It reports all is OK
```
The certificate currently available on matoda.pw is OK. It is not one of the certificates affected by the Let's Encrypt CAA rechecking problem. Its serial number is 0441135e65894cd3d5be770538851661fdff
The certificate currently available on slack.conraid.net is OK. It is not one of the certificates affected by the Let's Encrypt CAA rechecking problem. Its serial number is 03d2b1185edcaaca7489dccb5686f8c9010e
The certificate currently available on slackware.nl is OK. It is not one of the certificates affected by the Let's Encrypt CAA rechecking problem. Its serial number is 04268fc55484f59e4e35b9d358f79184e93b
```
But **sl-feeds** works well with AlienBob mirrror
The only difference is the key size of his public key : 4096 vs. 2048 for conraid.net & mine
I don't know if it counts or not

**Comment by vbatts** [comment]
this is odd. It seems like it's not finding the root cert bundle, but https://github.com/golang/go/blob/master/src/crypto/x509/root_linux.go#L9 is the file that should exist on most linux hosts :thinking:

**Comment by maravtdm** [comment]
Ok
I got it 
Sorry for the inconvenience 
the script works fine on my slackware laptop
but not on my FreeBSD NAS, where I have the error

**Comment by vbatts** [comment]
ah! then it must have a different path for the system ca-certs ?

**Comment by maravtdm** [comment]
Apparently not ...
```
root:~/ freebsd-version -r
12.2-RELEASE-p6
root:~/ ls /etc/ssl/certs/*.crt
/etc/ssl/certs/ca-certificates.crt
```

I will continue to investigate & let you know

**Comment by maravtdm** [comment]
I there any option, for the sl-feeds stdout to be more verbose ?

**Comment by maravtdm** [comment]
Can it came from there ?

slack.conraid.net use the DST Root CA X3

FreeBSD :
```
root:~/ # ls -l /etc/ssl/certs/ | grep DST
lrwxr-xr-x 1 root wheel   51  6 avr.  22:27 2e5ac55d.0 -> ../../../usr/share/certs/trusted/DST_Root_CA_X3.pem
```
Slackware :
```
root:~/ # ls -l /etc/ssl/certs/ | grep DST
lrwxrwxrwx 1 root root   18 mars  26 08:01 2e5ac55d.0 -> DST_Root_CA_X3.pem
lrwxrwxrwx 1 root root   53 mars   8 20:47 DST_Root_CA_X3.pem -> /usr/share/ca-certificates/mozilla/DST_Root_CA_X3.crt
```

**Comment by vbatts** [comment]
couple of things here, if you're building this binary for BSD, then golang will be looking at a different location for the root bundle --> https://github.com/golang/go/blob/master/src/crypto/x509/root_bsd.go#L12

I just booted up a minimal virtualbox instance, and it looks like none of these paths are present by default.
![Screenshot from 2021-04-13 11-11-58](https://user-images.githubusercontent.com/67049/114576737-68d0eb80-9c49-11eb-8adb-0e0327aa3b38.png)

 You'll need to find which freebsd package provides system ca-certificates

**Comment by maravtdm** [comment]
Probably this one :
```
root:~/ # pkg info ca_root_nss-3.63
ca_root_nss-3.63
Name           : ca_root_nss
Version        : 3.63
Installed on   : Mon Apr 12 14:15:24 2021 CEST
Origin         : security/ca_root_nss
Architecture   : FreeBSD:12:*
Prefix         : /usr/local
Categories     : security
Licenses       : MPL20
Maintainer     : ports-secteam@FreeBSD.org
WWW            : UNKNOWN
Comment        : Root certificate bundle from the Mozilla Project
Options        :
        ETCSYMLINK     : on
Annotations    :
        repo_type      : binary
        repository     : FreeBSD
Flat size      : 759KiB
Description    :
Root certificates from certificate authorities included in the Mozilla
NSS library and thus in Firefox and Thunderbird.

This port directly tracks the version of NSS in the security/nss port.
```

**Comment by maravtdm** [comment]
root:~/ # cat /usr/ports/security/ca_root_nss/pkg-plist 
%%CERTDIR%%/ca-root-nss.crt
@sample etc/ssl/cert.pem.sample
@sample openssl/cert.pem.sample
%%ETCSYMLINK%%/etc/ssl/cert.pem
%%ETCSYMLINK%%@dir /etc/ssl
@postexec [ ! -e %%LOCALBASE%%/bin/cert-sync ] || %%LOCALBASE%%/bin/cert-sync --quiet %%PREFIX%%/share/certs/ca-root-nss.crt

**Comment by maravtdm** [comment]
root:~/ # ls -l /usr/local/etc/ssl/
total 495
-rw-r--r-- 1 root wheel 786736 17 oct.  03:21 cert.pem
lrwxr-xr-x 1 root wheel     33 27 mars  02:23 cert.pem.sample -> ../../share/certs/ca-root-nss.crt

**Comment by maravtdm** [comment]
FYI, It's almost a pretty clean NAS under FreeBSD, not far from your minimal install, with only few services enable, like samba & nginx, a media server (Plex) and Transmission in background - sharing 14.2 salckware iso - waiting for the 15.0 ... :-)

**Comment by maravtdm** [comment]
Hello,
I do not see what is wrong with the Let's Encrypt certificate (on my Domain Name and on conraid.net) and especially why there is no concern with AlienBob's one
I won't bother you any longer
I have deported the RSS feed to my mirror in http

**Comment by maravtdm** [comment]
Hi,
Just a last question :
Is there any possibilities to fetch the URL with a kind of insecure option, as for curl (-k) or wget (--no-check-certificate) ?

**Comment by vbatts** [comment]
@maravtdm alrighty. I've opened a change (#19) for both allowing to specify an exact CA cert file to the trusted set (which is obviously more secure), as well as an `--insecure` that just doesn't check (very insecure).
